#if UNITY_EDITOR
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEditor.AddressableAssets.Settings.GroupSchemas;
using UnityEngine;
using UnityEngine.Profiling;

namespace VladislavTsurikov.AddressableGroupGenerator.Editor
{
    public static class AddressableGroupGenerator
    {
        public static void CreateGroupsFromContent(string rootPath, int limit, int folderDepth, bool filterByExtension,
            string extensionFilter)
        {
            var targetFolders = Directory.GetDirectories(rootPath, "*", SearchOption.AllDirectories)
                .Where(folder =>
                    PathRulesUtility.GetFolderDepth(folder, rootPath) == folderDepth &&
                    ContentFolderUtility.IsValidContentFolder(folder))
                .ToArray();

            AddressableAssetSettings settings = AddressableAssetSettingsDefaultObject.GetSettings(false);

            AssetDatabase.StartAssetEditing();
            try
            {
                var total = targetFolders.Length;
                var processedCount = 0;

                for (var i = 0; i < total; i++)
                {
                    if (limit != -1 && i >= limit)
                    {
                        break;
                    }

                    Profiler.BeginSample("Create Addressable Group");

                    var folder = targetFolders[i];
                    var rawGroupName = ContentFolderUtility.GetGroupName(folder);
                    var groupName = GroupNameConvention.ToAutoGroupName(rawGroupName);

                    AddressableAssetGroup group = settings.FindGroup(groupName) ??
                                                  settings.CreateGroup(groupName, false, false, false, null,
                                                      typeof(BundledAssetGroupSchema));

                    AssetEntryUtility.AddAssetsToGroup(folder, group, groupName, filterByExtension, extensionFilter);

                    processedCount++;

                    EditorUtility.DisplayProgressBar("Creating Addressable Groups", folder,
                        (float)processedCount / total);

                    Profiler.EndSample();
                }
            }
            finally
            {
                AssetDatabase.StopAssetEditing();
                EditorUtility.ClearProgressBar();
                AssetDatabase.SaveAssets();
                Debug.Log("Addressable Groups created.");
            }
        }

        public static void RemoveAutoGeneratedGroups(AddressableAssetSettings settings)
        {
            var toRemove = settings.groups
                .Where(g => g != null && GroupNameConvention.IsAutoGeneratedGroup(g.Name))
                .ToList();

            foreach (AddressableAssetGroup group in toRemove)
            {
                settings.RemoveGroup(group);
                Debug.Log($"Removed auto-generated group: {group.Name}");
            }
        }
    }
}
#endif
