#if ADDRESSABLE_LOADER_SYSTEM_ADDRESSABLES
#if UNITY_EDITOR
namespace VladislavTsurikov.AddressableGroupGenerator.Editor
{
    public static class GroupNameConvention
    {
        private const string AutoGroupPrefix = "ALS_";

        public static string ToAutoGroupName(string rawName) => $"{AutoGroupPrefix}{rawName}";

        public static bool IsAutoGeneratedGroup(string groupName) => groupName.StartsWith(AutoGroupPrefix);
    }
}
#endif
#endif
