#if UNITY_EDITOR
namespace VladislavTsurikov.AddressableGroupGenerator.Editor
{
    public static class GroupNameConvention
    {
        private const string AutoGroupPrefix = "ALS_";

        public static string ToAutoGroupName(string rawName)
        {
            return $"{AutoGroupPrefix}{rawName}";
        }

        public static bool IsAutoGeneratedGroup(string groupName)
        {
            return groupName.StartsWith(AutoGroupPrefix);
        }
    }
}
#endif